// ===========================================================================
// Copyright 2016 Autodesk, Inc. All rights reserved.
//
// Use of this software is subject to the terms of the Autodesk license
// agreement provided at the time of installation or download, or which
// otherwise accompanies this software in either electronic or hard copy form.
// ===========================================================================
//
//
//  Creation Date:  Feb 7 2013
//
//  Description:
//      This script is called from TmayaApp::initAfter() for HUD initialization.
//
{
	source initHUDScripts.mel;

	// Object Details

	headsUpDisplay -s 4
		-b 0
		-vis (`optionVar -q objectDetailsVisibility`)
		-label  (uiRes("m_initHUD.kHUDTitleBackfaces"))
		-lw 135
		-dw 75
		-c "objectDetailsBackfaces()"
		-ev "SelectionChanged"
		-nc "attributeChange"
		HUDObjDetBackfaces;

	headsUpDisplay -s 4
		-b 1
		-vis (`optionVar -q objectDetailsVisibility`)
		-label  (uiRes("m_initHUD.kHUDTitleSmoothness"))
		-lw 135
		-dw 75
		-c "objectDetailsSmoothness()"
		-ev "SelectionChanged"
		-nc "attributeChange"
		HUDObjDetSmoothness;

	headsUpDisplay -s 4
		-b 2
		-vis (`optionVar -q objectDetailsVisibility`)
		-label (uiRes("m_initHUD.kHUDTitleInstance"))
		-lw 135
		-dw 75
		-c "objectDetailsInstance()"
		-ev "SelectionChanged"
		-nc "instanceChange"
		HUDObjDetInstance;

	headsUpDisplay -s 4
		-b 3
		-vis (`optionVar -q objectDetailsVisibility`)
		-label (uiRes("m_initHUD.kHUDTitleDisplayLayer"))
		-lw 135
		-dw 75
		-c "objectDetailsDisplayLayer()"
		-ev "SelectionChanged"
		-nc "connectionChange"
		HUDObjDetDispLayer;

	headsUpDisplay -s 4
		-b 4
		-vis (`optionVar -q objectDetailsVisibility`)
		-label (uiRes("m_initHUD.kHUDTitleDistanceFromCamera"))
		-lw 135
		-dw 75
		-pre "distanceFromCamera"
		HUDObjDetDistFromCam;

	headsUpDisplay -s 4
		-b 5
		-vis (`optionVar -q objectDetailsVisibility`)
		-label (uiRes("m_initHUD.kHUDTitleSelectedObjects"))
		-lw 135
		-dw 75
		-c "objectDetailsNumberOfSelectedObjects()"
		-ev "SelectionChanged"
		HUDObjDetNumSelObjs;

	// Poly Count

	headsUpDisplay -s 0
		-b 0
		-vis (`optionVar -q polyCountVisibility`)
		-label (uiRes("m_initHUD.kHUDTitleVerts"))
		-lw 50
		-dw 65
		-da "right"
		-pre "polyVerts"
		HUDPolyCountVerts;

	headsUpDisplay -s 0
		-b 1
		-vis (`optionVar -q polyCountVisibility`)
		 -label (uiRes("m_initHUD.kHUDTitleEdges"))
		-lw 50
		-dw 65
		-da "right"
		-pre "polyEdges"
		HUDPolyCountEdges;

	headsUpDisplay -s 0
		-b 2
		-vis (`optionVar -q polyCountVisibility`)
		-label (uiRes("m_initHUD.kHUDTitleFaces"))
		-lw 50
		-dw 65
		-da "right"
		-pre "polyFaces"
		HUDPolyCountFaces;

	headsUpDisplay -s 0
		-b 3
		-vis (`optionVar -q polyCountVisibility`)
		 -label (uiRes("m_initHUD.kHUDTitleTris"))
		-lw 50
		-dw 65
		-da "right"
		-pre "polyTriangles"
		HUDPolyCountTriangles;

	headsUpDisplay -s 0
		-b 4
		-vis (`optionVar -q polyCountVisibility`)
		 -label (uiRes("m_initHUD.kHUDTitleUVs"))
		-lw 50
		-dw 65
		-da "right"
		-pre "polyUVs"
		HUDPolyCountUVs;

	// Subd details

	headsUpDisplay -s 0
		-b 5
		-vis (`optionVar -q subdDetailsVisibility`)
		-label (uiRes("m_initHUD.kHUDTitleSubdivCurrentLevel"))
		-lw 135
		-dw 30
		-c "subdDetailsCurrentLevel()"
		-ev "SelectionChanged"
		-nc "attributeChange"
		HUDSubdLevel;

	headsUpDisplay -s 0
		-b 6
		-vis (`optionVar -q subdDetailsVisibility`)
		-label (uiRes("m_initHUD.kHUDTitleSubdivMode"))
		-lw 135
		-dw 30
		-c "subdDetailsCurrentMode()"
		-ev "SelectionChanged"
		HUDSubdMode;

	headsUpDisplay -s 0
		-b 7
		-vis (`optionVar -q particleCountVisibility`)
		-label (uiRes("m_initHUD.kHUDTitleParticleCount"))
		-lw 50
		-dw 130
		-da "right"
		-c "getParticleCount()"
		-atr
		HUDParticleCount;

	// exclude getParticleCount from command history since it is called on each refresh
	if (!stringArrayContains("getParticleCount", `commandEcho -q -filter`)) {
		commandEcho -addFilter "getParticleCount";
	}

	// Camera Names
	headsUpDisplay -s 7
		-b 0
		-vis (`optionVar -q cameraNamesVisibility`)
		-ao true
		-ba center
		-pre "cameraNames"
		HUDCameraNames;

	// This HUD is used to display the string.
	// Its visibility is toggled in toggleHWRendererModelPanel()
	// and the setViewportRendererVisibility().
	headsUpDisplay -s 2
		-b 1
		-vis (`optionVar -q viewportRendererVisibility`)
		-ba center
		-label (uiRes("m_initHUD.kHUDTitleCameraName"))
		-pre "viewportRenderer"
		HUDViewportRenderer;

	headsUpDisplay -s 2
		-b 2
		-vis (`optionVar -q symmetryVisibility`)
		-ba center
		-preset "symmetry"
		HUDSymmetry;

	headsUpDisplay -s 2
		-b 3
		-vis (`optionVar -q capsLockVisibility`)
		-ba center
		-c "getCapsLockState()"
		-atr
		HUDCapsLock;

	// exclude getCapsLockState from command history since it is called on each refresh
	if (!stringArrayContains("getCapsLockState", `commandEcho -q -filter`)) {
		commandEcho -addFilter "getCapsLockState";
	}

	int $section = 9;
	int $lblWidth = 115;
	int $block = 0;

	// Frame Rate
	headsUpDisplay -s $section
		-b $block
		-vis (`optionVar -q frameRateVisibility`)
		-ba right
		-dfs large
		-da right
		-dp 1
		-pre "frameRate"
		HUDFrameRate;
	$block++;

	// GPU Override
	headsUpDisplay
		-section $section
		-labelWidth $lblWidth
		-dataWidth 95
		-b $block
		-vis (`optionVar -q evaluationVisibility`)
		-label (uiRes("m_initHUD.kHUDLabelOpenCLOverride"))
		-labelFontSize small
		-pre "gpuOverride"
		HUDGPUOverride;
	$block++;

	// EM State
	headsUpDisplay
		-section $section
		-labelWidth $lblWidth
		-dataWidth 95
		-b $block
		-vis (`optionVar -q evaluationVisibility`)
		-label (uiRes("m_initHUD.kHUDLabelEMState"))
		-labelFontSize small
		-pre "emState"
		HUDEMState;
	$block++;

	// Evaluation
	headsUpDisplay
		-section $section
		-labelWidth $lblWidth
		-dataWidth 95
		-b $block
		-vis (`optionVar -q evaluationVisibility`)
		-label (uiRes("m_initHUD.kHUDLabelEvaluation"))
		-labelFontSize small
		-pre "evaluation"
		HUDEvaluation;
	$block++;

	int $mldVisibility = `optionVar -q materialLoadingDetailsVisibility`;
	headsUpDisplay -s $section
		-b $block
		-label (uiRes("m_initHUD.kHUDTexturesToLoad"))
		-dp 1
		-dfs "small"
		-lw $lblWidth
		-dw 75
		-pre "textureLoadingCount"
		-vis $mldVisibility
		HUDLoadingTextures;
	$block++;

	headsUpDisplay -s $section
		-b $block
		-label (uiRes("m_initHUD.kHUDMaterialsToLoad"))
		-dp 1
		-dfs "small"
		-lw $lblWidth
		-dw 75
		-pre "materialLoadingCount"
		-vis $mldVisibility
		HUDLoadingMaterials;
	$block++;

	// Register warning message.
	scriptJob -e "serialExecutorFallback" "WarnAboutSerialExecutionFallback;";

	// Current Frame
	headsUpDisplay -section $section
		-block				$block
		-blockSize			"small"
		-label				(uiRes("m_initHUD.kHUDCurrentFrameLabel"))
		-labelWidth			$lblWidth
		-dataWidth			75
		-labelFontSize		"small"
		-dataFontSize		"small"
		-allowOverlap		true
		-preset				"currentFrame"
		-vis				(`optionVar -q currentFrameVisibility`)
		HUDCurrentFrame;
	$block++;

	// Animation Stuff

	headsUpDisplay -s $section
		-b $block
		-label (uiRes("m_initHUD.kHUDTitleIKBlend"))
		-dp 1
		-dfs "small"
		-lw $lblWidth
		-dw 75
		-c "animationDetailsIKFK()"
		-ev "SelectionChanged"
		-nc "attributeChange"
		HUDIKSolverState;
	$block++;

	headsUpDisplay -s $section
		-b $block
		-label (uiRes("m_initHUD.kHUDTitleCurrentCharacter"))
		-dp 1
		-dfs "small"
		-lw $lblWidth
		-dw 75
		-c "animationDetailsCurrentCharacter()"
		-ev "NewSceneOpened"
		HUDCurrentCharacter;
	$block++;

	headsUpDisplay -s $section
		-b $block
		-label (uiRes("m_initHUD.kHUDTitlePlaybackSpeed"))
		-dp 1
		-dfs "small"
		-lw $lblWidth
		-dw 75
		-c "animationDetailsPlaybackSpeed()"
		-ev "timeUnitChanged"
		HUDPlaybackSpeed;
	$block++;

	headsUpDisplay -s $section
		-b $block
		-label (uiRes("m_initHUD.kHUDHikKeyingMode"))
		-dp 1
		-dfs "small"
		-lw $lblWidth
		-dw 75
		-c "hikDetailsKeyingMode()"
		-ev "SelectionChanged"
		HUDHikKeyingMode;
	$block++;

	headsUpDisplay -s $section
		-b $block
		-label (uiRes("m_initHUD.kHUDFbikKeyType"))
		-dp 1
		-dfs "small"
		-lw $lblWidth
		-dw 75
		-c "fbikDetailsKeyType()"
		-ev "SelectionChanged"
		HUDFbikKeyType;
	$block++;

	headsUpDisplay -section $section
		-block $block
		-vis (`optionVar -q selectDetailsVisibility`)
		-lw $lblWidth
		-preset "softSelect"
		HUDSoftSelectState;
	$block++;

	// Current container
	headsUpDisplay -section $section
		-block				$block
		-blockSize			"small"
		-label				(uiRes("m_initHUD.kHUDCurrentContainerLabel"))
		-labelWidth			$lblWidth
//		-dataWidth			75
		-labelFontSize		"small"
		-dataFontSize		"small"
		-command			"getCurrentContainer"
		-event				"currentContainerChange"
		-vis (`optionVar -q currentContainerVisibility`)
		HUDCurrentContainer;
	$block++;

	// None of the above animation HUDs had their visibility
	// set according to the option var.  Do that now...
	//
	setAnimationDetailsVisibility(`optionVar -q animationDetailsVisibility`);
	setFbikDetailsVisibility(`optionVar -q fbikDetailsVisibility`);
	setHikDetailsVisibility(`optionVar -q hikDetailsVisibility`);

	headsUpDisplay -section $section
		-block $block
		-vis (`optionVar -q focalLengthVisibility`)
		-preset "focalLength"
		-lw $lblWidth
		HUDFocalLength;
	$block++;

	// Scene Timecode
	headsUpDisplay -section $section
		-block				$block
		-blockSize			"small"
		-label				(uiRes("m_initHUD.kHUDSceneTimecodeLabel"))
		-labelWidth			$lblWidth
		-dataWidth			75
		-labelFontSize		"small"
		-dataFontSize		"small"
		-allowOverlap		true
		-preset				"sceneTimecode"
		-vis (`optionVar -q sceneTimecodeVisibility`)
		HUDSceneTimecode;
	$block++;

	// View Axis
	headsUpDisplay -s 5
		-b 0
		-vis (`optionVar -q viewAxisVisibility`)
		-pre "viewAxis"
		HUDViewAxis;

	// Origin Axis
	// It is toggled on/off here rather than in initialGUI.mel because:
	// 1. initialGUI.mel is for batch mode only while initHUD.mel is for both batch mode and GUI mode.
	// 2. Origin Axis checkbox is located under Heads Up Display menu and next to View Axis checkbox.
	// 3. Origin Axis is functionally similar to View Axis.
	toggleAxis -o `optionVar -q toggleOriginAxis`;
	
	headsUpDisplay -s 7
		-b 1
		-vis false
		-label	(uiRes("m_initHUD.kHUDWalkModeLabel"))
		-allowOverlap		true
		HUDWalkMode;
	
	headsUpDisplay -s 7
		-b 3
		-vis false
		-allowOverlap true
		HUDBlendShapeEdit;

	scriptJob -event SceneOpened updateBlendShapeEditHUD;

	headsUpDisplay -s 7
		-b 2
		-vis false
		-allowOverlap		true
		HUDActiveSculptMesh;

	headsUpDisplay -s 7
		-b 4
		-vis false
		-allowOverlap		true
		HUD3DCutSewUVActiveMesh;
}
